name: CI

on:
  pull_request:      

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build
      run: go build -v ./...

    - name: Run Tests and Generate a Coverage Report
      run: go test ./... -coverprofile=coverage.out

    - name: Run Go Linter (golangci-lint)
      uses: golangci/golangci-lint-action@v5
      with:
        version: latest 

    - name: Upload coverage with Octocov
      uses: k1LoW/octocov-action@v1
      with:
        config: ./.octocov.yml